name: Bulk Projects Creation

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
    - cron: '*/15 * * * *'
    - cron: '*/30 * * * *'

jobs:
  install-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Create multiple projects
        run: |
          for i in {1..10}; do
            TIMESTAMP=$(date +'%Y%m%d%H%M%S%N')
            PROJECT_DIR="nextjs-project-$TIMESTAMP"
            
            # Create Next.js project
            npx create-next-app@latest $PROJECT_DIR --use-npm --no-tailwind --no-eslint --no-src-dir --no-experimental-app --ts --no-import-alias &
          done
          wait

      - name: Install dependencies and modify files
        run: |
          for project in nextjs-project-*; do
            cd $project
            npm install react-theme-switch-animation
            echo "// Added by GitHub Actions" >> README.md
            cd ..
          done

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name 'githubdungchung'
          git config --global user.email '165872053+githubdungchung@users.noreply.github.com'
          git add .
          git commit -m "Initialize multiple Next.js projects and install react-theme-switch-animation"
          git push -f https://githubdungchung:${{ secrets.PAT }}@github.com/githubdungchung/trigger.git HEAD:main
