name: Check and Trigger Batch Creation

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Check for running workflows
      id: check_workflows
      run: |
        # Get the list of running workflows
        response=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
                  "https://api.github.com/repos/${{ github.repository }}/actions/runs?status=in_progress")
        # Parse the total count of running workflows
        running_count=$(echo $response | jq '.total_count')
        echo "Total running workflows: $running_count"
        echo "::set-output name=running_count::$running_count"

    - name: Trigger Batch Creation Workflow
      if: steps.check_workflows.outputs.running_count == '0'
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/batch_creation_of_commits.yml/dispatches \
          -d '{"ref":"main"}'
