name: Clean Repo

on:
  push:
    branches:
      - main

jobs:
  clean_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: false

      - name: Remove All Files
        run: |
          git rm -rf .
          rm -rf .*

      - name: Commit Changes
        run: |
          git config --global user.name 'githubdungchung'
          git config --global user.email '165872053+githubdungchung@users.noreply.github.com'
          git commit -m "Clean repo"

      - name: Push Changes
        env:
          GH_PAT: ${{ secrets.PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git push origin main --force
