name: Clear Repository

on:
  push:
    branches:
      - main

jobs:
  clear-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: false

      - name: Remove all files except .github/workflows and .git directory
        run: |
          shopt -s extglob
          rm -rf !( .git| .github )
          git config --global user.name 'githubdungchung'
          git config --global user.email '165872053+githubdungchung@users.noreply.github.com'
          git add .
          git commit -m "Removed all files except .github/workflows and .git"
          git push origin main
