name: Bulk Commit With Py

on:
  workflow_dispatch:

jobs:
  create-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          token: ${{ secrets.PAT }}
          persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Configure Git
      run: |
        git config --global user.name 'githubdungchung'
        git config --global user.email '165872053+githubdungchung@users.noreply.github.com'

    - name: Create Python script
      run: |
        echo "import subprocess" > create_commits.py
        echo "def create_commits(number_of_commits):" >> create_commits.py
        echo "    subprocess.run(['git', 'config', '--global', 'user.name', 'githubdungchung'])" >> create_commits.py
        echo "    subprocess.run(['git', 'config', '--global', 'user.email', '165872053+githubdungchung@users.noreply.github.com'])" >> create_commits.py
        echo "    for i in range(1, number_of_commits + 1):" >> create_commits.py
        echo "        subprocess.run(['git', 'commit', '--allow-empty', '-m', f'Empty commit {i}'])" >> create_commits.py
        echo "    subprocess.run(['git', 'pull', '--rebase'])" >> create_commits.py
        echo "    subprocess.run(['git', 'push', '-f', 'https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git', 'HEAD:main'])" >> create_commits.py
        echo "if __name__ == '__main__':" >> create_commits.py
        echo "    create_commits(1000)" >> create_commits.py  # Adjust the number of commits as needed

    - name: Run create_commits.py
      run: python create_commits.py
